language: ruby
cache: bundler
rvm:
  - 2.7.0
addons:
  postgresql: "12.2"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_scripts:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database math115_travis_ci_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
env:
  global:
  - PGPORT=5433
