# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: math115_development

test:
  <<: *default
  database: math115_test

production:
  <<: *default
  database: math115_production
  username: math115
  password: <%= ENV['MATH115_DATABASE_PASSWORD'] %>
